<?php
// $Id:
/**
 * @file
 */

/**
 * Implements hook_views_api().
 */
function views_infinite_scroll_views_api() {
  return array('api' => '3.0-alpha1');
}

/**
 * Implements hook_theme().
 */
function views_infinite_scroll_theme() {
  $path = drupal_get_path('module', 'views_infinite_scroll');

  // Some quasi clever array merging here.
  $base = array(
    'file' => 'views_infinite_scroll_theme.inc',
    'path' => "$path/theme",
  );

  // Our extra version of pager from pager.inc
  $hooks['views_infinite_scroll_pager'] = $base + array(
    'variables' => array(
      'tags' => array(),
      'limit' => 10,
      'element' => 0,
      'parameters' => array(),
    ),
    'pattern' => 'views_infinite_scroll_pager__',
  );
  return $hooks;
}

/**
* Implements hook_libraries_info
*
* Provides autopager and html5shiv
*/
function views_infinite_scroll_libraries_info() {
  $libraries = array(
    'autopager' => array(
      'name' => 'jQuery Autopager',
      'vendor url' => 'http://code.google.com/p/jquery-autopager/',
      'download url' => 'http://code.google.com/p/jquery-autopager/',
      'dependencies' => array('html5shiv'),
      'version' => '1.0',
      'files' => array(
        'js' => array('jquery.autopager-1.0.0.js'),
        'css' => array('autopager.css'),
      ),
    ),
    'html5shiv' => array(
      'name' => 'html5shiv',
      'vendor url' => 'http://code.google.com/p/html5shiv/',
      'download url' => 'http://code.google.com/p/html5shiv/',
      'version' => '1.0',
      'files' => array('js' => array('html5shiv.js')),
    ),
  );
  
  return $libraries;
}
